baseurl = "http://moos-ivp.github.io/open-docs/"
languageCode = "en-us"
title = "MOOS-IvP Open-Docs"
theme = "docs"
metadataformat = "yaml"
canonifyurls = true

googleAnalytics = ""

[params]
  # General information
  author = "MOOS-IvP team & contributors"
  description = "Open Documentations for the MOOS-IvP marine autonomy suite."
  copyright = "Released under the MIT license"

  # Repository
  provider = "GitHub"
  repo_url = "https://github.com/moos-ivp/MOOS-IvP-releases"

  version = "15.5"
  logo = "images/head.jpg"
  favicon = "favicon2.ico"

  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "blue"
      accent  = "blue"

  [params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"


[social]
  twitter = "moosivp"
  github  = "moos-ivp"


[[menu.main]]
  name   = "Open Documentation"
  url    = "/"
  weight = 0

[[menu.main]]
  name   = "Contributing"
  url    = "contributing/"
  weight = 10

[[menu.main]]
  name   = "Community Apps"
  url    = "communityapps/"
  weight = 20

[[menu.main]]
  name   = "Use Cases & Demos"
  url    = "usecases/"
  weight = 30

[[menu.main]]
  name   = "License"
  url    = "license/"
  weight = 40


[blackfriday]
  smartypants  = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
